import Image from 'next/image';
import Link from 'next/link';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Blog',
  description: 'Read our latest articles',
};

const blogPosts = [
  {
    id: 1,
    title: 'Music GPT Review: Create Hit Songs Instantly with AI Song Generator',
    excerpt: "Music GPT Review: Create Hit Songs Instantly with AI Song Generator Music GPT is the kind of tool that makes things feel surprisingly simple if you have ever wanted to make music but didn't know where to begin. It's for people...",
    date: 'MAY 06',
    image: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?q=80&w=600&auto=format&fit=crop', // placeholder abstract music vibe
    href: '#',
  },
  {
    id: 2,
    title: 'Best Tools to Find Exact & Similar Image Matches for Verification',
    excerpt: 'Need to verify an image? Explore six reverse image search tools that help find matches, trace origins, and detect edits across the web easily. 6 Best Tools to Find Exact & Similar Image Matches for Verification Images move...',
    date: 'MAY 05',
    image: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?q=80&w=600&auto=format&fit=crop', // placeholder magnifying/code vibe
    href: '#',
  },
  {
    id: 3,
    title: '09 Free AI Kissing Video Generators',
    excerpt: 'Explore kissing scenes generated by AI for free. These 09 free AI kissing video generator delivers lifelike kissing clips with user-friendly controls and fast rendering. Experiment with different moods, outfits, and settings to fit your narrative—no expensive software...',
    date: 'DEC 31',
    image: 'https://images.unsplash.com/photo-1517457373958-b7bdd4587205?q=80&w=600&auto=format&fit=crop', // placeholder couple vibe
    href: '#',
  },
];

export default function BlogPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] pt-32 pb-16 px-4 sm:px-6 lg:px-8">
      <div className="max-w-7xl mx-auto">
        <h1 className="text-[32px] font-semibold text-center text-white mb-12">Blog</h1>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          {blogPosts.map((post) => (
            <article key={post.id} className="bg-[#111113] rounded-[10px] shadow-sm overflow-hidden flex flex-col border border-white/10 hover:border-white/20 transition-all duration-300">
              <div className="relative h-64 w-full group">
                <Link href={post.href}>
                  <Image
                    src={post.image}
                    alt={post.title}
                    fill
                    className="object-cover group-hover:scale-105 transition-transform duration-300"
                    unoptimized
                  />
                </Link>
                <div className="absolute top-4 left-4">
                  <div className="bg-black/40 backdrop-blur-md border border-white/20 text-white px-2 py-1.5 rounded-lg flex flex-col items-center leading-none shadow-sm min-w-[3rem]">
                    <span className="text-[10px] tracking-wider font-medium mb-1 uppercase">{post.date.split(' ')[0]}</span>
                    <span className="text-lg font-bold">{post.date.split(' ')[1]}</span>
                  </div>
                </div>
              </div>
              <div className="p-8 flex flex-col flex-grow">
                <Link href={post.href}>
                  <h2 className="text-lg font-semibold text-white text-center mb-4 hover:text-[#6366f1] transition-colors line-clamp-2 leading-snug">
                    {post.title}
                  </h2>
                </Link>
                <p className="text-gray-400 text-sm text-center line-clamp-4 leading-relaxed mb-4">
                  {post.excerpt}
                </p>
              </div>
            </article>
          ))}
        </div>
      </div>
    </div>
  );
}
